-- Migration: add hands, hand_cards, tricks, scores tables
-- Safe to run multiple times (CREATE TABLE IF NOT EXISTS).

CREATE TABLE IF NOT EXISTS hands (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  game_id BIGINT UNSIGNED NOT NULL,
  hand_number INT UNSIGNED NOT NULL,
  dealer_seat TINYINT UNSIGNED NOT NULL,
  deck_seed BIGINT UNSIGNED NOT NULL,
  kitty_json JSON NOT NULL,
  bid_winner_seat TINYINT UNSIGNED NULL,
  bid_value SMALLINT UNSIGNED NULL,
  is_30_for_60 TINYINT(1) NOT NULL DEFAULT 0,
  trump_suit CHAR(1) NULL,
  phase VARCHAR(40) NOT NULL DEFAULT 'bidding',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uq_game_hand UNIQUE (game_id, hand_number),
  CONSTRAINT fk_hands_game FOREIGN KEY (game_id) REFERENCES games(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS hand_cards (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  hand_id BIGINT UNSIGNED NOT NULL,
  seat TINYINT UNSIGNED NOT NULL,
  cards_json JSON NOT NULL,
  CONSTRAINT uq_hand_seat UNIQUE (hand_id, seat),
  CONSTRAINT fk_hand_cards_hand FOREIGN KEY (hand_id) REFERENCES hands(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS tricks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  hand_id BIGINT UNSIGNED NOT NULL,
  trick_number TINYINT UNSIGNED NOT NULL,
  lead_seat TINYINT UNSIGNED NOT NULL,
  winner_seat TINYINT UNSIGNED NULL,
  cards_json JSON NOT NULL,
  best_trump_played CHAR(3) NULL,
  CONSTRAINT uq_hand_trick UNIQUE (hand_id, trick_number),
  CONSTRAINT fk_tricks_hand FOREIGN KEY (hand_id) REFERENCES hands(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS scores (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  game_id BIGINT UNSIGNED NOT NULL,
  hand_id BIGINT UNSIGNED NOT NULL,
  team0_delta SMALLINT NOT NULL DEFAULT 0,
  team1_delta SMALLINT NOT NULL DEFAULT 0,
  team0_total SMALLINT NOT NULL DEFAULT 0,
  team1_total SMALLINT NOT NULL DEFAULT 0,
  team0_sets TINYINT UNSIGNED NOT NULL DEFAULT 0,
  team1_sets TINYINT UNSIGNED NOT NULL DEFAULT 0,
  CONSTRAINT uq_score_hand UNIQUE (hand_id),
  CONSTRAINT fk_scores_game FOREIGN KEY (game_id) REFERENCES games(id),
  CONSTRAINT fk_scores_hand FOREIGN KEY (hand_id) REFERENCES hands(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
